-- Aslim Boutique Supabase/Postgres schema
-- Supabase SQL Editor'da tek sefer çalıştırılabilir.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  phone text not null default '',
  email_verified_at timestamptz,
  password_hash text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  image text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  sku text not null default '',
  description text not null default '',
  price numeric(12, 2) not null default 0,
  compare_price numeric(12, 2),
  stock integer not null default 0,
  images jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  variant_images jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);


create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  order_no text not null unique,
  customer_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  city text not null,
  district text not null default '',
  neighborhood text not null default '',
  street text not null default '',
  building_no text not null default '',
  floor text not null default '',
  apartment_no text not null default '',
  postal_code text not null default '',
  notes text not null default '',
  payment_method text not null default 'WhatsApp',
  status text not null default 'Yeni',
  tracking_code text not null default '',
  cancel_reason text not null default '',
  subtotal numeric(12, 2) not null,
  shipping numeric(12, 2) not null,
  total numeric(12, 2) not null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null
);

create index if not exists idx_products_active_created on public.products(active, created_at desc);
create index if not exists idx_products_category on public.products(category_id);
create index if not exists idx_orders_created on public.orders(created_at desc);
create index if not exists idx_orders_user on public.orders(user_id);
create index if not exists idx_sessions_expires on public.sessions(expires_at);

insert into public.users (email, name, password_hash, role, email_verified_at)
values (
  'aslimboutique@gmail.com',
  'Aslım Yönetici',
  '1d3454c8c5fb1190157cc2365e38d4ec:d57c0f68a3acc4d4436d78fc4c2fbbae152d1dd22fdc4e1e24e325f68676850ba469159949a15686478eef4025332446ca1060583fb253a9ad8435eb63a3324c',
  'admin',
  now()
)
on conflict (email) do update set role = 'admin';

insert into public.settings (key, value) values
  ('storeName', '"ASLIM BOUTIQUE"'::jsonb),
  ('announcement', '"AÇILIŞA ÖZEL İNDİRİM"'::jsonb),
  ('announcements', '["AÇILIŞA ÖZEL İNDİRİM"]'::jsonb),
  ('logo', '"/images/logo.webp"'::jsonb),
  ('heroTitle', '"Zarafetin yeni hali"'::jsonb),
  ('heroSubtitle', '"Günün her anına eşlik eden seçkin parçaları keşfedin."'::jsonb),
  ('heroButton', '"KOLEKSİYONU KEŞFET"'::jsonb),
  ('heroImages', '["/images/hero-scarf.webp", "/images/hero-vest.webp", "/images/hero-bag.webp"]'::jsonb),
  ('authImage', '"/images/hero-vest.webp"'::jsonb),
  ('authEyebrow', '"ASLIM BOUTIQUE"'::jsonb),
  ('authLoginTitle', '"Tekrar hoş geldiniz."'::jsonb),
  ('authLoginText', '"Hesabınıza giriş yaparak favorilerinize devam edin."'::jsonb),
  ('authRegisterTitle', '"Aramıza katılın."'::jsonb),
  ('authRegisterText', '"Favorilerinizi saklamak için hesabınızı oluşturun."'::jsonb),
  ('phone', '"+90 555 555 55 55"'::jsonb),
  ('email', '"info@aslimboutique.com"'::jsonb),
  ('instagram', '"https://instagram.com/aslimboutiquetr"'::jsonb),
  ('whatsapp', '"905555555555"'::jsonb),
  ('address', '"İstanbul, Türkiye"'::jsonb),
  ('shippingFee', '89.9'::jsonb),
  ('freeShippingThreshold', '1500'::jsonb),
  ('returnDays', '15'::jsonb),
  ('trustTitle1', '"Güvenli alışveriş"'::jsonb),
  ('trustText1', '"256 Bit SSL koruması"'::jsonb),
  ('trustTitle2', '"Hızlı gönderim"'::jsonb),
  ('trustText2', '"Özenli ve takipli teslimat"'::jsonb),
  ('trustTitle3', '"Kolay iade"'::jsonb),
  ('trustText3', '"3 iş günü içinde"'::jsonb),
  ('faqItems', '[{"question":"Nasıl satın alabilirim?","answer":"Ürün sayfasındaki Satın Al butonu sizi WhatsApp görüşmesine yönlendirir."}]'::jsonb),
  ('footerNote', '"Özenle seçilmiş zamansız parçalar."'::jsonb),
  ('primaryColor', '"#0a0a0a"'::jsonb),
  ('accentColor', '"#a4743b"'::jsonb)
on conflict (key) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'aslim-boutique',
  'aslim-boutique',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do nothing;

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
alter default privileges in schema public grant all privileges on tables to service_role;
alter default privileges in schema public grant all privileges on sequences to service_role;

